services:
  - type: web
    name: medisynai-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyDXSHzvrnXywPLUFMTVxFQGfdbvamxF6zI